#!/usr/bin/env python3
"""Export the string catalog for SwiftPM toolchains that copy xcstrings without compiling them."""
import argparse
import json
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parent.parent / 'Sources/SwiftUICalendar/Resources'
catalog = json.loads((root / 'Localizable.xcstrings').read_text())
languages = {}
for key, entry in sorted(catalog['strings'].items()):
    for language, translation in entry.get('localizations', {}).items():
        value = translation['stringUnit']['value']
        languages.setdefault(language, []).append(f'{json.dumps(key, ensure_ascii=False)} = {json.dumps(value, ensure_ascii=False)};\n')
for language, lines in languages.items():
    output = root / f'{language}.lproj' / 'Localizable.strings'
    content = '// Generated by scripts/export-localizations.py. Edit Localizable.xcstrings.\n' + ''.join(lines)
    if args.check:
        if not output.exists() or output.read_text() != content:
            raise SystemExit(f'Outdated localization: {output}')
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)
